name: Update badges

on:
  workflow_dispatch:
  schedule:
    # Runs at 0am UTC every day
    - cron: "0 2 * * *"
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: Taillan/badge-readme@main
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          BADGE_SIZE: 100
          NUMBER_LAST_BADGES: 24
          REPOSITORY: Taillan/Taillan
          COMMIT_MESSAGE: "Updated README with new badges locally"
          CREDLY_USER: taillandier-math-tail-outlook-fr
