
name: updateReadme

on:
  push:
    # only trigger on branches, not on tags
    branches: '**'
  workflow_dispatch:
  schedule:
    - cron: '0 0 */2 * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - name: Use Node.js
      uses: actions/setup-node@v4.0.0
      with:
        node-version: '14.x'
    - name: Update README.md
      run: node index.js > README.md
    - name: Commit change & Push
      run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git commit -am "bot: update README.md automatically"
          git push
  update-readme:
    needs: build
    permissions: write-all
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: Taillan/badge-readme@main
        with:
          GH_TOKEN: ${{ github.token }}
          BADGE_SIZE: 150
          NUMBER_LAST_BADGES: 24
          REPOSITORY: Taillan/Taillan
          COMMIT_MESSAGE: "Updated README with new badges locally"
          CREDLY_USER: taillandier-math-tail-outlook-fr
